common: &common
  adapter: postgresql
  username:
  password:

development:
  <<: *common
  database: arkham_utils_development

test: &test
  <<: *common
  database: arkham_utils_test

production:
  <<: *common
  database: arkham_utils_production

cucumber:
  <<: *test